# config/app.yml for rails-settings-cached
defaults: &defaults
  sendgrid_key: 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

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
